query GetFolderById($id: UUID!) {
    folderById(id: $id) {
        id
        user {
            email
            id
        }
        name
        createdAt
        parentFolder {
            id
            name
        }
    }
    folders(parentFolderId: $id) {
        id
        name
        createdAt
    }
    files(folderId: $id) {
        id
        name
        file
        size
        createdAt
    }
}
